### ISSUE TITLE
Can't Get Past Chapter 1 - Please Help! 

### ISSUE THREAD

**Issue by drdexter33** [bradleyd/devops_for_the_desperate#30]
I recently bought the book DevOps for the Desparate and cannot get past chapter 1 exercises and I've gone through the exercises multiple times now.

Per the introduction instructions on page xiv:

I am running the examples in a Windows 11 Pro - Hyper - V Ubuntu VM.
I've tried the following OS's

1. Ubuntu 18.04 LTS
2. Ubuntu 20.04 LTS
3. Ubuntu 22.04 LTS

![image](https://github.com/bradleyd/devops_for_the_desperate/assets/15314276/36b98a1f-245b-4081-88bf-78e5c92f6c6d)

(Not in the instructions)
When the Hyper-V image is created, I resized the hard drive to 100GB in Hyper-V setting since I was running out of space when I ran 
`$vagrant up`

After I resized the hard drive in Hyper-V I also needed to resize the Linux partition which I did.

![image](https://github.com/bradleyd/devops_for_the_desperate/assets/15314276/67742b57-9a91-4f74-9aaf-4b23e6e9c9f8)

All of the other steps I completed successfully, IE:

Page xiv
`Set-VMProcessor -VMName 'Ubuntu 20.04 LTS' -ExposeVirtualizationExtensions $true` 

Page xxi
`$git clone https://github.com/bradleyd/devops_for_the_desperate/`

Page 4
Installed Vagrant

Page 7
Installed Ansible

Page 9
'$ vagrant up'

I've been getting different errors, but now I am getting this one:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/focal64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/focal64' version '20230719.0.0' is up to date...
==> default: Setting the name of the VM: dftd
==> default: Clearing any previously set network interfaces...
**There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "vboxnet2", "--ip", "172.28.128.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp**

I can't move on to the next chapter since evertything from this point is dependent on getting this set up correctly.

PS:  There is a VM in VirtualBox, but I don't think it's working:

![image](https://github.com/bradleyd/devops_for_the_desperate/assets/15314276/30440dda-64be-49b8-bc92-f6315b655b24)

**Comment by drdexter33** [comment]
I've even tried to create a new VirtualBox VM without the vagrantfile in the Hyper-V VM and am not having any success.

**Comment by drdexter33** [comment]
Tried again and for some reason it's hanging here:

`
=> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/user/devops_for_the_desperate/vagrant
`

**Comment by davincent** [comment]
I am also having similar issues. I have had more success with Ubuntu 20.04 LTS and VirtualBox v6.1. What versions are you using?

**Comment by drdexter33** [comment]
22.04 LTS
VB 6.1

**Comment by drdexter33** [comment]
We can't be the only ones running into issues

**Comment by drdexter33** [comment]
![image](https://github.com/bradleyd/devops_for_the_desperate/assets/15314276/073179bd-0990-49a5-91ec-ef6e00b0a8af)

**Comment by davincent** [comment]
You'll need to use Ubuntu 20.04. Vagrant had an issue with 22.04. I didn't screenshot the message unfortunately.

**Comment by drdexter33** [comment]
Did you get yours to work?

**Comment by drdexter33** [comment]
Dropped down to 20.04.

Now getting this:
![image](https://github.com/bradleyd/devops_for_the_desperate/assets/15314276/caddf5d5-3e7e-4dad-bf85-d9a6a2593d0f)

**Comment by davincent** [comment]
I did manage to get mine to work. But I noticed I had to be in the vagrant directory and use 'sudo vagrant up'. Don't forget to install ansible.

**Comment by bradleyd** [comment]
Just checking in, is the issue resolved?

**Comment by drdexter33** [comment]
No...I kind of gave up on it and moved on..
Could never get it to work...
It would just hang

**Comment by bradleyd** [comment]
That stinks. 

I noticed the use of `sudo` on vagrant up. This should never be used as it will change the .vagrant files to be owned by root. 

Just to be clear, you installed virtualbox and vagrant in the ubuntu 20.04 vm running in hyper-v, correct?

@drdexter33 the error you are seeing is most likely the remnants of the failed virtualbox runs. If I recall, because of the failed up's (possibly with sudo) there is network interfaces in virtualbox that need to be removed. Go into the tools menu and remove any interfaces/networks. 

You might want to do a `sudo rm -rf .virtualbox` (I think that is the name of the dir?) and `devops_for_the_desperate/vagrant/.vagrant` directory as well to get a clean slate. 

Just use Ubuntu 20.04 since Vagrant had issues with 22.04, maybe fixed by now?

I really hope this helps you get passed Chapter 1. There is so much more interesting tasks in the later chapters.

**Comment by davincent** [comment]
I had a feeling sudo wasn't the intended method. I'll go through it again from the beginning to figure were I went wrong. I appreciate the feedback.

**Comment by bradleyd** [comment]
Please reopen if you need help.
