### ISSUE TITLE
[Apple M1 Pro] SSH connection refused upon Debian login via QEMU

### ISSUE THREAD

**Issue by diffeo-christopher** [bradleyd/devops_for_the_desperate#31]
OS: OS X 13.5.2 (22G91)
Following the README, I executed:

Command: 
```qemu-system-aarch64 -cpu cortex-a72 -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=2048 -m 2G -initrd initrd.img-5.10.0-11-arm64 -kernel vmlinuz-5.10.0-11-arm64 -append "root=/dev/vda2 console=ttyAMA0" -drive if=virtio,file=debian-dftd-aarch64.qcow2,format=qcow2,id=hd -net user,hostfwd=tcp::10022-:22,hostfwd=tcp::20375-:2375,hostfwd=tcp::5001-:5000 -net nic -device intel-hda -device hda-duplex -nographic```
(I changed memory from 4G to 2G)

Attempt to login with SSH:
```Last login: Sun Sep 10 16:49:04 MDT 2023 from 127.0.0.1 on pts/0
dftd@debian:~$ ssh dftd@127.0.0.1 -p 10022
ssh: connect to host 127.0.0.1 port 10022: Connection refused
dftd@debian:~$
```
Is this expected?

**Comment by bradleyd** [comment]
Hey @diffeo-christopher. When you run the `qemu-system-aarch64` command, you are dropped right into the running VM. You can tell by your shell prompt `dftd@debian`. There would be no need to SSH into the host from that shell. You can open another tab in your terminal and try there.

Thanks for supporting me and the book!

Let me know how it goes.

**Comment by bradleyd** [comment]
Please reopen if you need help.
