### ISSUE TITLE
M1 Pro Issues with network.

### ISSUE THREAD

**Issue by femiir** [bradleyd/devops_for_the_desperate#33]
i am using M1 mac and here is my qemu commands that works 

i aliased it though 

```
alias qemu-devops='qemu-system-aarch64 -cpu cortex-a72 -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=2048 -m 2G -initrd initrd.img-5.10.0-11-arm64 -kernel vmlinuz-5.10.0-11-arm64 -append "root=/dev/vda2 console=ttyAMA0" -drive if=virtio,file=debian-dftd-aarch64.qcow2,format=qcow2,id=hd -net user,hostfwd=tcp::10022-:22,hostfwd=tcp::20375-:2375,hostfwd=tcp::5001-:5000 -net nic -device intel-hda -device hda-duplex -nographic'
```

i do not know much but from the error i am getting i am thinking its a network issue cause when i run my qemu command 
and i try to run the ansible playbook to set it up i get the following error on the the qemu shell 

```audit: type=1400 audit(1706215476.240:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="docker-default" pid=407 comm="apparmor_parser"
[   19.457612] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[   19.459610] Bridge firewalling registered
[   19.557540] Initializing XFRM netlink socket
[   56.165252] systemd-journald[190]: File /var/log/journal/c2ab053aa964497ba825c6ea95ed73c8/user-1000.journal corrupted or uncleanly shut down, renaming and replacing.
```

**Comment by bradleyd** [comment]
Hey @femiir, that is a new one to me. Let me try what you have and see. I have not encountered this before.

**Comment by femiir** [comment]
> Hey @femiir, that is a new one to me. Let me try what you have and see. I have not encountered this before.

thank you 
i have been unable to continue with the book 😔 ...

**Comment by bradleyd** [comment]
@femiir I just followed the README for Qemu Apple silicon and it worked for me. I am on MacOS 14.4.1. Macbook Pro M3.

Can you ssh into the VM after you run the qemu command?

**Comment by femiir** [comment]
please can you point for reference me to the the section of the document

**Comment by bradleyd** [comment]
Are you able to ssh once you launch it?

Here is the link but I am sure you are already following it: https://github.com/bradleyd/devops_for_the_desperate/tree/main/apple-silicon/qemu

**Comment by femiir** [comment]
Thank you so much i was able to continue with the book and program…
