### ISSUE TITLE
Chapter 3: [errata] group `bender`

### ISSUE THREAD

**Issue by storenth** [bradleyd/devops_for_the_desperate#34]
Possible errata found on https://github.com/bradleyd/devops_for_the_desperate/blob/93066ab97c4e285a7e1d25591eb397031059093e/ansible/chapter3/two_factor.yml#L12

We created `developers` under *Ensure group 'developers' exists* task but use `bender` now didn't get it, can you explain please?

There is no side effect I think:
![bender-issue](https://github.com/bradleyd/devops_for_the_desperate/assets/18244131/0865bfcd-affc-45c9-a25a-785154c20574)

**Comment by bradleyd** [comment]
@storenth Thanks for reading the book! What you are showing there is correct. When you run `getent` for group `bender`, it returns the group ID 1003. The `developers` group will have a different ID. In your case it is 1002. In the group file, right after the 1002 group ID for `developers`, you have a `:`. Following this is the list of users that are associated with this group. In this case, you can see `bender` is a member of the developers group. Each group will have a unique ID to that host.

I hope that helps.

Brad

**Comment by storenth** [comment]
> Possible errata found on
> 
> https://github.com/bradleyd/devops_for_the_desperate/blob/93066ab97c4e285a7e1d25591eb397031059093e/ansible/chapter3/two_factor.yml#L12
> 
> We created `developers` under _Ensure group 'developers' exists_ task but use `bender` now didn't get it, can you explain please?


But, why you do not use `developers` under 12 line of the *Copy over Preconfigured GoogleAuthenticator config* task? Thanks for assist, I'm glad to hear you.

**Comment by bradleyd** [comment]
Because I only wanted to show how to setup GA for the bender user.
