### ISSUE TITLE
Chapter 4-5: `nginx` line just for practical reasons?

### ISSUE THREAD

**Issue by storenth** [bradleyd/devops_for_the_desperate#35]
Actually `nginx` is not used, I removed the line `nginx` from the task and pass the chapter 4 and 5
https://github.com/bradleyd/devops_for_the_desperate/blob/93066ab97c4e285a7e1d25591eb397031059093e/ansible/chapter4/web_application.yml#L7
@bradleyd do you added `nginx` line just for reasons of installing packages? Thank you.

**Comment by bradleyd** [comment]
Yes, to show how to via CM
