### ISSUE TITLE
vagrant-vbguest (0.32.0) is no longer maintained and it contains bugs for curent vagrant (2.3.4) on fedora 40

### ISSUE THREAD

**Issue by dheerapat** [bradleyd/devops_for_the_desperate#36]
`vagrant-vbguest` (0.32.0) is no longer maintained and it contains bugs for current vagrant (2.3.4) on fedora 40

you will encounter `NoMethodError` after you run command `vagrant up` and your VM will not instantiated.

for quick fix if you still want to use this plugin is go to
`.vagrant.d/gems/3.3.1/gems/vagrant-vbguest-0.32.0/lib/vagrant-vbguest/hosts/virtualbox.rb` on your home directory
and fix `File.exists?` into `File.exist?` on line 84

I try to publish new plugin that already fix this issue but ruby is not my field of expertise. But in my opinion you can follow along the book just fine without this unmaintained plugin installed.

**Comment by dheerapat** [comment]
I [forked](https://github.com/dheerapat/vagrant-vbguest/tree/main) the plugin source code and update it into a new version 0.32.1 and provided a guide on how to build and install plugin locally in the first part of read me file.

**Comment by bradleyd** [comment]
Thanks. I think people may be able to try it without it.
