### ISSUE TITLE
Understanding ansible-playbook section

### ISSUE THREAD

**Issue by jonbry** [bradleyd/devops_for_the_desperate#37]
I don't have an issue with any of the code in the book, but I was wondering if someone could explain the ansible-playbook code in a bit more detail (in Basic Ansible Commands):

`ansible-playbook -l dockerhosts aws-cloudwatch.yml`

What is `dockerhosts` and `aws-cloudwatch.yml` and where do they exist? I scoured the web, but none of the results looked quite right. 

Also, is the inventory file mentioned in the book called `vagrant_ansible_inventory` that's located in `/devops_for_the_desperate/vagrant/.vagrant/provisioners/ansible/inventory`?

Thank you!

**Comment by jonbry** [comment]
> What is `dockerhosts` and `aws-cloudwatch.yml` and where do they exist? I scoured the web, but none of the results looked quite right. 
> 
> 
> 
> Also, is the inventory file mentioned in the book called `vagrant_ansible_inventory` that's located in `/devops_for_the_desperate/vagrant/.vagrant/provisioners/ansible/inventory`?

- I found the answer to this one. Yes, this is where the [auto-generated inventory file is located](https://developer.hashicorp.com/vagrant/docs/provisioning/ansible_intro)

**Comment by bradleyd** [comment]
Thanks @jonbry for reading and reaching out.

Yeah, Vagrant, during provisioning, will create that file for us before executing the command.
